### ISSUE TITLE
Is DNS-module upper/lowercase agnostic?

### ISSUE THREAD

**Issue by mdavids** [SIDN/spin#25]

**Comment by tjeb** [comment]
It is now; in practice it didn't really matter, since the different casings of domains would be associated to the same node anyway, but it was inefficient in terms of internal memory and data packet sizes (especially since some systems use case variation a lot). Internally, domain names are now stored case-insensitively, commit 4168f2d1e37365dd7521aa96dbd5becabb3d92b7
