### ISSUE TITLE
Nodes have incorrect color

### ISSUE THREAD

**Issue by ElmerLastdrager** [SIDN/spin#27]
Code:
```
$ dig valibox. A
$ curl -4 valibox. >/dev/null
```
Result:
![screen shot 2018-02-26 at 14 48 32](https://user-images.githubusercontent.com/1679693/36673766-22d23f22-1b04-11e8-91fd-db6ed2c8a02c.png)

Expected result:
"Valibox." to be green, and the ipv4 to be assigned to it.

**Comment by ElmerLastdrager** [comment]
After consulting @tjeb: this may be by-design (since valibox traffic is ignored). However, for DNS queries, valibox-traffic is not ignored.

Question is: how do we proceed?
We should probably ignore Valibox DNS queries as well, at least in the GUI.

**Comment by tjeb** [comment]
actually, come to think of it, this will happen with any IP address that is in the ignore list; DNS queries that resolve to that IP will still be shown, but the traffic will not. I am leaning towards ignoring those queries too but it doesn't really feel right...

**Comment by ElmerLastdrager** [comment]
+1 for hiding the dns queries. That's what ignore implies. @mdavids ?

**Comment by tjeb** [comment]
Hmm. The generalized approach needs an additional set of protocol messages from the kmod to spind (updates to ignore/block/except lists), or the hard assumption that spind is the only one talking to the kmod. We will need those anyway (if/when we want host-based lists) but it feels out of scope for this particular issue (that is to say, i don't want to rush that to get this fixed). I *could* hard-special-case these particular names but I rather not. If we run into this again before extending the protocol we can do that. Otherwise I want to close this and add it to #42
