### ISSUE TITLE
Install instructions is unclear 

### ISSUE THREAD

**Issue by johanhenselmans** [SIDN/spin#65]
In the install document there is an instruction that tells to install 

apt-get install libmosquitto-dev luarocks install lua-mosquitto luabitop luaposix

In Debian there is no lua-mosquitto. lua itself has to be chosen between lua5.0, lua5.1 and lua5.2
i changed it to: 
apt-get  install libmosquitto-dev lua5.1 luarocks mosquitto lua-bitop lua-posix
luarocks install lua-mosquitto

Also in the document, the instruction 
git clone https://github.com/SIDN/spin.git
is missing when compiling the source code. 

Also
apt get install libnetfilter-log-dev libnetfilter-log1 
should be included

and 
apt-get install libnetfilter-conntrack-dev libnetfilter-conntrack3
apt-get install libldns-dev

**Comment by johanhenselmans** [comment]
As it turns out, the dev branch has the real instructions, which are a bit different. 

There is still the issue of modprobe nf_conntrack_ipv4 nf_conntrack_ipv6. I am running buster on a raspberrypi, could only find nf_conntrack.
Oh, and the sentence 
apt-get install libmosquitto-dev luarocks install lua-mosquitto luabitop luaposix
has to be separated to 
apt-get install libmosquitto-dev luarocks
luarocks install lua-mosquitto lua-websockets luabitop luaposix lua-minittp

**Comment by tjeb** [comment]
yeah, the dev branch has better ones, but some of them probably don't apply to the main branch, so I was hestitant to point to that.

Furthermore, we'll probably need to split it up into a few separate lists of instructions, for a few OS'es, since, as you've noticed, they can be different; package names are one, config files can be another (on some systems, for instance, mosquitto has a conf.d subdirectory to place config snippets in, but on others there's only the main mosquitto.conf file)

I suspect that on raspbian those kernelmodules were baked in, so they don't need to be loaded, but I am not entirely sure.

Anyway, thanks for the findings, i'll try to make them better when we release the dev version; any other suggestions are of course welcome too

**Comment by johanhenselmans** [comment]
Regarding nf_conntrack: I checked on an Ubuntu 18.0.4.3 LTS installation: that one also only contains nf_conntrack,ko. There is nf_conntrack_ipv4.h and nf_conntrack_ipv6.h, but apparently the stuff than gets combined in one kernel module. This was a 5.0.0.31 kernel. 

CentOS7.6 (with a 3.10 kernel) still has a nf_conntrack_ipv4 and nf_conntrack_ipv6. 
Debian 9 (kernel 4.19) on an ARM machine also has nf_conntrack combined.

**Comment by tjeb** [comment]
I have updated the readme (now also in master). For the next version we'll need to consider making separate instructions for a few specific os'es, as the details do seem to differ quite a bit.
